//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class screen2 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture26;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture27;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text25;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture28;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text26;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture29;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture30;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text27;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private bool m_Initialized_screen2;
        
        public screen2() {
            this.InitializeComponent();
            this.m_MultiPicture5.MouseDown += new System.EventHandler(this.m_MultiPicture5_Action_MouseDown);
            this.m_MultiPicture5.MouseUp += new System.EventHandler(this.m_MultiPicture5_Action_MouseUp);
            this.m_MultiPicture26.MouseDown += new System.EventHandler(this.m_MultiPicture26_Action_MouseDown);
            this.m_MultiPicture26.MouseUp += new System.EventHandler(this.m_MultiPicture26_Action_MouseUp);
            this.m_MultiPicture27.MouseDown += new System.EventHandler(this.m_MultiPicture27_Action_MouseDown);
            this.m_MultiPicture27.MouseUp += new System.EventHandler(this.m_MultiPicture27_Action_MouseUp);
            this.m_MultiPicture28.MouseUp += new System.EventHandler(this.m_MultiPicture28_Action_MouseUp);
            this.m_MultiPicture28.MouseDown += new System.EventHandler(this.m_MultiPicture28_Action_MouseDown);
            this.m_MultiPicture29.MouseUp += new System.EventHandler(this.m_MultiPicture29_Action_MouseUp);
            this.m_MultiPicture29.MouseDown += new System.EventHandler(this.m_MultiPicture29_Action_MouseDown);
            this.m_MultiPicture30.MouseUp += new System.EventHandler(this.m_MultiPicture30_Action_MouseUp);
            this.m_MultiPicture30.MouseDown += new System.EventHandler(this.m_MultiPicture30_Action_MouseDown);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture26 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture26);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture27 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture27);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text25 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text25);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture28 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture28);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text26 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text26);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture29 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture29);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture30 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture30);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text27 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text27);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_MultiPicture5 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_MultiPicture26 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture27 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text25 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_MultiPicture28 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text26 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_MultiPicture29 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture30 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text27 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture26)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture27)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text25)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture28)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text26)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture29)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture30)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text27)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            this.SuspendLayout();
            // 
            // screen2
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15))))), System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(91)))), ((int)(((byte)(91))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 25;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 22;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "screen2";
            this.m_Text2.Top = 54;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 54;
            // 
            // m_MultiPicture5
            // 
            this.m_MultiPicture5.BlinkDynamicsValue = false;
            this.m_MultiPicture5.DelayMouseInputPeriod = 0;
            this.m_MultiPicture5.EnabledDynamicsValue = true;
            this.m_MultiPicture5.Height = 54;
            this.m_MultiPicture5.Left = 487;
            this.m_MultiPicture5.Name = "m_MultiPicture5";
            this.m_MultiPicture5.ScreenOwnerName = "screen2";
            symbolinterval1.End = 255D;
            multisymbolitem1.SymbolName = "button 2a";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolintervalmapper1.Intervals.Add(symbolinterval1);
            this.m_MultiPicture5.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_MultiPicture5.SymbolName = "button 2a";
            this.m_MultiPicture5.Top = 199;
            this.m_MultiPicture5.Value = 0D;
            this.m_MultiPicture5.VisibleDynamicsValue = true;
            this.m_MultiPicture5.Width = 70;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 25;
            this.m_Text5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 312;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "screen2";
            this.m_Text5.Top = 208;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 35;
            // 
            // m_Text10
            // 
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.DelayMouseInputPeriod = 0;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontSizePixels = 25;
            this.m_Text10.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text10.Height = 21;
            this.m_Text10.Left = 25;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.ScreenOwnerName = "screen2";
            this.m_Text10.Top = 280;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 62;
            // 
            // m_MultiPicture26
            // 
            this.m_MultiPicture26.BlinkDynamicsValue = false;
            this.m_MultiPicture26.DelayMouseInputPeriod = 0;
            this.m_MultiPicture26.EnabledDynamicsValue = true;
            this.m_MultiPicture26.Height = 54;
            this.m_MultiPicture26.Left = 175;
            this.m_MultiPicture26.Name = "m_MultiPicture26";
            this.m_MultiPicture26.ScreenOwnerName = "screen2";
            symbolinterval2.End = 255D;
            multisymbolitem2.SymbolName = "button 2a";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolintervalmapper2.Intervals.Add(symbolinterval2);
            this.m_MultiPicture26.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_MultiPicture26.SymbolName = "button 2a";
            this.m_MultiPicture26.Top = 45;
            this.m_MultiPicture26.Value = 0D;
            this.m_MultiPicture26.VisibleDynamicsValue = true;
            this.m_MultiPicture26.Width = 124;
            // 
            // m_MultiPicture27
            // 
            this.m_MultiPicture27.BlinkDynamicsValue = false;
            this.m_MultiPicture27.DelayMouseInputPeriod = 0;
            this.m_MultiPicture27.EnabledDynamicsValue = true;
            this.m_MultiPicture27.Height = 54;
            this.m_MultiPicture27.Left = 202;
            this.m_MultiPicture27.Name = "m_MultiPicture27";
            this.m_MultiPicture27.ScreenOwnerName = "screen2";
            symbolinterval3.End = 255D;
            multisymbolitem3.SymbolName = "button 2a";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolintervalmapper3.Intervals.Add(symbolinterval3);
            this.m_MultiPicture27.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_MultiPicture27.SymbolName = "button 2a";
            this.m_MultiPicture27.Top = 122;
            this.m_MultiPicture27.Value = 0D;
            this.m_MultiPicture27.VisibleDynamicsValue = true;
            this.m_MultiPicture27.Width = 70;
            // 
            // m_Text25
            // 
            this.m_Text25.BlinkDynamicsValue = false;
            this.m_Text25.DelayMouseInputPeriod = 0;
            this.m_Text25.EnabledDynamicsValue = true;
            this.m_Text25.FontSizePixels = 25;
            this.m_Text25.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text25.Height = 21;
            this.m_Text25.Left = 312;
            this.m_Text25.Name = "m_Text25";
            this.m_Text25.ScreenOwnerName = "screen2";
            this.m_Text25.Top = 63;
            this.m_Text25.VisibleDynamicsValue = true;
            this.m_Text25.Width = 76;
            // 
            // m_MultiPicture28
            // 
            this.m_MultiPicture28.BlinkDynamicsValue = false;
            this.m_MultiPicture28.DelayMouseInputPeriod = 0;
            this.m_MultiPicture28.EnabledDynamicsValue = true;
            this.m_MultiPicture28.Height = 54;
            this.m_MultiPicture28.Left = 175;
            this.m_MultiPicture28.Name = "m_MultiPicture28";
            this.m_MultiPicture28.ScreenOwnerName = "screen2";
            symbolinterval4.End = 255D;
            multisymbolitem4.SymbolName = "button 2a";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolintervalmapper4.Intervals.Add(symbolinterval4);
            this.m_MultiPicture28.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_MultiPicture28.SymbolName = "button 2a";
            this.m_MultiPicture28.Top = 199;
            this.m_MultiPicture28.Value = 0D;
            this.m_MultiPicture28.VisibleDynamicsValue = true;
            this.m_MultiPicture28.Width = 124;
            // 
            // m_Text26
            // 
            this.m_Text26.BlinkDynamicsValue = false;
            this.m_Text26.DelayMouseInputPeriod = 0;
            this.m_Text26.EnabledDynamicsValue = true;
            this.m_Text26.FontSizePixels = 25;
            this.m_Text26.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text26.Height = 21;
            this.m_Text26.Left = 25;
            this.m_Text26.Name = "m_Text26";
            this.m_Text26.ScreenOwnerName = "screen2";
            this.m_Text26.Top = 208;
            this.m_Text26.VisibleDynamicsValue = true;
            this.m_Text26.Width = 70;
            // 
            // m_MultiPicture29
            // 
            this.m_MultiPicture29.BlinkDynamicsValue = false;
            this.m_MultiPicture29.DelayMouseInputPeriod = 0;
            this.m_MultiPicture29.EnabledDynamicsValue = true;
            this.m_MultiPicture29.Height = 54;
            this.m_MultiPicture29.Left = 175;
            this.m_MultiPicture29.Name = "m_MultiPicture29";
            this.m_MultiPicture29.ScreenOwnerName = "screen2";
            symbolinterval5.End = 255D;
            multisymbolitem5.SymbolName = "button 2a";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolintervalmapper5.Intervals.Add(symbolinterval5);
            this.m_MultiPicture29.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_MultiPicture29.SymbolName = "button 2a";
            this.m_MultiPicture29.Top = 271;
            this.m_MultiPicture29.Value = 0D;
            this.m_MultiPicture29.VisibleDynamicsValue = true;
            this.m_MultiPicture29.Width = 124;
            // 
            // m_MultiPicture30
            // 
            this.m_MultiPicture30.BlinkDynamicsValue = false;
            this.m_MultiPicture30.DelayMouseInputPeriod = 0;
            this.m_MultiPicture30.EnabledDynamicsValue = true;
            this.m_MultiPicture30.Height = 54;
            this.m_MultiPicture30.Left = 487;
            this.m_MultiPicture30.Name = "m_MultiPicture30";
            this.m_MultiPicture30.ScreenOwnerName = "screen2";
            symbolinterval6.End = 255D;
            multisymbolitem6.SymbolName = "button 2a";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolintervalmapper6.Intervals.Add(symbolinterval6);
            this.m_MultiPicture30.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_MultiPicture30.SymbolName = "button 2a";
            this.m_MultiPicture30.Top = 54;
            this.m_MultiPicture30.Value = 0D;
            this.m_MultiPicture30.VisibleDynamicsValue = true;
            this.m_MultiPicture30.Width = 70;
            // 
            // m_Text27
            // 
            this.m_Text27.BlinkDynamicsValue = false;
            this.m_Text27.DelayMouseInputPeriod = 0;
            this.m_Text27.EnabledDynamicsValue = true;
            this.m_Text27.FontSizePixels = 25;
            this.m_Text27.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text27.Height = 21;
            this.m_Text27.Left = 22;
            this.m_Text27.Name = "m_Text27";
            this.m_Text27.ScreenOwnerName = "screen2";
            this.m_Text27.Top = 131;
            this.m_Text27.VisibleDynamicsValue = true;
            this.m_Text27.Width = 46;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 15;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 64;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 735;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "screen2";
            this.m_Button.SymbolHeight = 54;
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button.SymbolName = "bb_arrow left";
            this.m_Button.SymbolWidth = 54;
            this.m_Button.TextHeight = 18;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 54;
            this.m_Button.Top = 1;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1141215080;
            this.m_Button.Width = 64;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.DelayMouseInputPeriod = 0;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "screen2";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 286;
            this.m_Line.X2 = 287;
            this.m_Line.Y1 = 21;
            this.m_Line.Y2 = 343;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "screen2";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_screen2 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_screen2) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_MultiPicture5);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_MultiPicture26);
            this.DrawingPrimitives.Add(this.m_MultiPicture27);
            this.DrawingPrimitives.Add(this.m_Text25);
            this.DrawingPrimitives.Add(this.m_MultiPicture28);
            this.DrawingPrimitives.Add(this.m_Text26);
            this.DrawingPrimitives.Add(this.m_MultiPicture29);
            this.DrawingPrimitives.Add(this.m_MultiPicture30);
            this.DrawingPrimitives.Add(this.m_Text27);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Line);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture26)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture27)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text25)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture28)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text26)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture29)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture30)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text27)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
        }
        
        private void m_MultiPicture5_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture5", "MouseDown", "Set Tag", "Tags.Purge_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Purge_toggle.SetTag();
        }
        
        private void m_MultiPicture5_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture5", "MouseUp", "Reset Tag", "Tags.Purge_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Purge_toggle.ResetTag();
        }
        
        private void m_MultiPicture26_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture26", "MouseDown", "Set Tag", "Tags.Heat_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Heat_toggle.SetTag();
        }
        
        private void m_MultiPicture26_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture26", "MouseUp", "Reset Tag", "Tags.Heat_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Heat_toggle.ResetTag();
        }
        
        private void m_MultiPicture27_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture27", "MouseDown", "Set Tag", "Tags.Cooling_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Cooling_toggle.SetTag();
        }
        
        private void m_MultiPicture27_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture27", "MouseUp", "Reset Tag", "Tags.Cooling_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Cooling_toggle.ResetTag();
        }
        
        private void m_MultiPicture28_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture28", "MouseUp", "Reset Tag", "Tags.Wet_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Wet_toggle.ResetTag();
        }
        
        private void m_MultiPicture28_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture28", "MouseDown", "Set Tag", "Tags.Wet_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Wet_toggle.SetTag();
        }
        
        private void m_MultiPicture29_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture29", "MouseUp", "Reset Tag", "Tags.Dry_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Dry_toggle.ResetTag();
        }
        
        private void m_MultiPicture29_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture29", "MouseDown", "Set Tag", "Tags.Dry_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Dry_toggle.SetTag();
        }
        
        private void m_MultiPicture30_Action_MouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture30", "MouseUp", "Reset Tag", "Tags.Water_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Water_toggle.ResetTag();
        }
        
        private void m_MultiPicture30_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture30", "MouseDown", "Set Tag", "Tags.Water_toggle", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Water_toggle.SetTag();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "scren1", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.scren1.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(screen2));
            this.m_Text2.Text = resources.GetText("screen2.Text2.Text", "Temp ++");
            this.m_Text5.Text = resources.GetText("screen2.Text5.Text", "Purge");
            this.m_Text10.Text = resources.GetText("screen2.Text10.Text", "Humidity --");
            this.m_Text25.Text = resources.GetText("screen2.Text25.Text", "Fill water tank");
            this.m_Text26.Text = resources.GetText("screen2.Text26.Text", "Humidity ++");
            this.m_Text27.Text = resources.GetText("screen2.Text27.Text", "Temp --");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_screen2) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Wet_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture28.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Dry_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture29.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Water_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture30.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Purge_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture5.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Heat_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture26.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Cooling_toggle"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture27.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
        }
    }
}
